# Generated by Django 5.2.5 on 2025-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('contactno', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
